name: flutter_tawk
description: Tawk widget for Flutter.
version: 0.0.5
homepage: https://github.com/ayoubamine/flutter_tawk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

